config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
  root to: 'restaurants#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    restaurant_type = ["chinese", "italian", "japanese", "french", "belgian"]
    has_many :reviews, dependent: :destroy
    validates :name, :address, :category, presence: true
    validates :category, inclusion: { in: restaurant_type }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates  :restaurant, :content, presence: true
  validates  :rating, presence: true
  validates  :rating, inclusion: { in: (0..5) }, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
      if @restaurant.save
        redirect_to restaurant_path(@restaurant)
      else
        render :new
      end
  end

  private


  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :find_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
    redirect_to restaurant_path(@restaurant)
    else
    render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end 

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.button :submit, :class => "btn btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
  <h1> Our Restaurants : </h1>
<ul>
      <% @restaurants.each do |restaurant| %>
      <li>
       <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2> 
        <p><%=restaurant.address%></p>
      </li>
      <% end %>
</ul>
<%=link_to "Add a restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%=@restaurant.name%></h1>
<p> <%=@restaurant.address%></p>
<p> <%=@restaurant.phone_number%></p>
<p> <%=@restaurant.category%></p>

<%=link_to "add review", new_restaurant_reviews_path(@restaurant) %>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit a review", class: "btn btn-primary" %>
<% end %>